/* Batalla de Bots · Nivel avanzado
   40 situaciones, 10 por bot. Cada caso es una experiencia real de uso contada por un estudiante: para acertar
   hay que haber usado los bots. Las pistas son comportamientos de la interfaz, avisos, límites y flujos de trabajo.
   Los ids deben ser 1..N contiguos: cada id es un sector de la ruleta.
   eje = ronda del debate de la Actividad 5.
   Verificado contra la documentación oficial de cada fabricante el 2 de octubre de 2026. */
(window.BANCOS = window.BANCOS || {}).avanzado = {
  nivel: 'avanzado',
  nombre: 'Nivel avanzado',
  clave: 'batallaBots_v2',          // clave de la partida guardada (se conserva la de la versión anterior)
  version: 2,
  rueda: { fuente: 28, radio: 0.86 },   // tamaño del número en cada sector de la ruleta
  txt: {
    resumen:   'Cada grupo gira la ruleta, escucha una experiencia real de uso y decide con qué bot ocurrió antes de que se acabe el tiempo. Para acertar hay que haber usado las IA: las pistas son avisos, límites y comportamientos de cada app.',
    pregunta:  '¿Con qué bot ocurrió esto?',
    decision:  'Es la única decisión que toma cada grupo: ¿con cuál pasó?',
    comoJugar: 'Gire la ruleta, lea la situación en voz alta y deje que el grupo decida. Al responder se revela la explicación y la fuente oficial que la sustenta. Hay <strong>{N}</strong> situaciones, diez de cada bot, repartidas en los cuatro ejes del debate: capacidades, limitaciones, generosidad e identidad. Ninguna se repite en la misma partida y el sorteo reparte los bots de forma pareja entre los grupos.',
    unidad:    'Situación',          // "Argumento 3 de 32"
    unidades:  'situaciones',
    sinUsar:   'Situaciones sin usar',
    girar:     'Giren la ruleta para recibir una situación.',
    alMenos:   'cada grupo necesita al menos una',
    noAlcanzan:'No alcanzan las situaciones',
    noQuedan:  'No quedan situaciones disponibles.',
    noExiste:  'La situación guardada ya no existe en esta versión del juego. Inicie una partida nueva.',
    revela:    'Fue con',          // "Lo dijo Claude (Anthropic)."
    ruleta:    'Ruleta de situaciones'
  },
  casos: [
    /* ===== CHATGPT · OpenAI ===== */
    { id: 1, a: 'CHATGPT', eje: 'Capacidades',
      t: 'Le pedí una ilustración para la portada de mi informe. La imagen no apareció de golpe: se fue revelando de arriba hacia abajo, borrosa al principio, mientras el chat indicaba que la estaba creando. Luego le escribí «quítale el texto y pon el fondo azul» y la editó ahí mismo, en la misma conversación, sin abrir otra herramienta.',
      e: 'El generador de imágenes integrado en ChatGPT dibuja la imagen de forma progresiva, de arriba hacia abajo, y permite editarla conversando. Gemini también genera imágenes, pero no con ese barrido progresivo.',
      r: 'help.openai.com · Creating images in ChatGPT' },
    { id: 2, a: 'CHATGPT', eje: 'Generosidad',
      t: 'Llevaba toda la tarde trabajando con la versión gratuita cuando apareció un aviso: había alcanzado el límite del modelo principal y, hasta cierta hora, las respuestas las daría un modelo más ligero. No me bloqueó: seguí conversando sin pausa, pero noté respuestas más cortas y menos cuidadosas en los temas difíciles.',
      e: 'En el plan gratuito de ChatGPT, al agotar el cupo del modelo principal la app pasa a un modelo más pequeño en vez de detener la conversación. Claude, en cambio, detiene el chat hasta que se reinicia el cupo.',
      r: 'help.openai.com · ChatGPT Free tier FAQ' },
    { id: 3, a: 'CHATGPT', eje: 'Capacidades',
      t: 'En un chat comenté que estudio mecatrónica y que prefiero los ejemplos en Python. Debajo de mi mensaje apareció una pequeña etiqueta que decía que la memoria se había actualizado. Semanas después, en una conversación totalmente nueva, me explicó un tema con ejemplos en Python sin que yo se lo pidiera.',
      e: 'La memoria de ChatGPT guarda datos del usuario entre conversaciones y lo avisa con la etiqueta «Memoria actualizada»; desde la configuración se pueden ver y borrar los recuerdos guardados.',
      r: 'help.openai.com · Memory FAQ' },
    { id: 4, a: 'CHATGPT', eje: 'Capacidades',
      t: 'En la sección de personalización me dejó escoger una «personalidad» predefinida para el asistente, con nombres como Cínico o Nerd, que cambian el tono de todas sus respuestas. Además tenía campos para contarle a qué me dedico y cómo quiero que me responda, y esas indicaciones se aplicaban en todos los chats nuevos.',
      e: 'ChatGPT ofrece personalidades predefinidas e instrucciones personalizadas que se aplican a todas las conversaciones.',
      r: 'help.openai.com · Customizing your ChatGPT personality' },
    { id: 5, a: 'CHATGPT', eje: 'Capacidades',
      t: 'Activé la investigación profunda para un informe sobre baterías de litio. Antes de arrancar no me mostró un plan para editar: me devolvió unas preguntas para aclarar el alcance, como qué país, qué periodo y qué nivel técnico. Cuando las respondí trabajó varios minutos por su cuenta y me entregó un informe largo con citas.',
      e: 'La investigación profunda de ChatGPT suele pedir aclaraciones antes de empezar. La de Gemini, en cambio, muestra un plan de investigación que el usuario edita y aprueba.',
      r: 'help.openai.com · Deep research in ChatGPT' },
    { id: 6, a: 'CHATGPT', eje: 'Limitaciones',
      t: 'Algunas veces, en lugar de darme una sola respuesta, me mostró dos versiones lado a lado y me preguntó cuál prefería. Elegí una y la conversación siguió con esa. Al principio creí que era un error de la página, pero es una forma en que su fabricante recoge la opinión de los usuarios para mejorar sus modelos.',
      e: 'ChatGPT presenta de vez en cuando dos respuestas para que el usuario elija la mejor; es retroalimentación para entrenar y evaluar modelos.',
      r: 'help.openai.com · Response comparison' },
    { id: 7, a: 'CHATGPT', eje: 'Identidad',
      t: 'En la barra lateral hay una opción para explorar asistentes que crearon otras personas y empresas: uno que escribe con normas APA, otro que hace diagramas, otro de una universidad. Al abrir uno, la conversación arranca con las instrucciones y archivos que le dejó su creador, y su nombre aparece arriba en lugar del modelo.',
      e: 'Son los GPTs: asistentes personalizados que se buscan en la tienda de GPTs. Gemini tiene asistentes propios (Gems), pero no un catálogo público de terceros.',
      r: 'openai.com/index/introducing-the-gpt-store/' },
    { id: 8, a: 'CHATGPT', eje: 'Capacidades',
      t: 'Para el proyecto final invité a tres compañeros a la misma conversación con la IA. Todos escribíamos en el mismo hilo, como en un grupo de mensajería, y el asistente participaba cuando lo mencionábamos o cuando veía que podía aportar, sin responder a cada mensaje entre nosotros. Cada uno veía el historial completo.',
      e: 'Los chats grupales de ChatGPT permiten que varias personas conversen con el asistente en un mismo hilo.',
      r: 'openai.com · Group chats in ChatGPT' },
    { id: 9, a: 'CHATGPT', eje: 'Capacidades',
      t: 'Una mañana abrí la app y encontré tarjetas con novedades que la IA había preparado durante la noche, sin que yo hiciera ninguna pregunta: avances sobre un tema que estuve estudiando, ideas para mi proyecto y recordatorios. Eran distintas cada día, basadas en mis conversaciones anteriores, y podía decirle qué temas quería ver más.',
      e: 'ChatGPT Pulse prepara actualizaciones proactivas cada día a partir de las conversaciones y la memoria del usuario.',
      r: 'openai.com/index/introducing-chatgpt-pulse/' },
    { id: 10, a: 'CHATGPT', eje: 'Limitaciones',
      t: 'Un compañero quería generar un video corto a partir de una descripción, como lo hacía el año pasado con la app de video de la misma empresa. Cuando lo intentó en 2026 descubrió que ese producto ya no existía: su fabricante lo había retirado y había apagado también su API, así que tuvo que usar otra herramienta.',
      e: 'OpenAI descontinuó Sora: la app y la web en abril de 2026 y la API en septiembre de 2026.',
      r: 'help.openai.com/en/articles/20001152' },

    /* ===== CLAUDE · Anthropic ===== */
    { id: 11, a: 'CLAUDE', eje: 'Generosidad',
      t: 'Con el plan gratuito, a mitad de un trabajo me salió un aviso: se me había acabado el cupo y podría volver a escribir a una hora determinada. No me pasó a un modelo más ligero: simplemente no pude seguir conversando hasta que el contador se reinició, unas horas después, y entonces retomé el mismo chat donde lo dejé.',
      e: 'Claude trabaja con límites por sesión que se reinician cada pocas horas; al agotarlos indica la hora en que se libera el cupo, en vez de cambiar a un modelo más pequeño.',
      r: 'support.claude.com · About usage limits' },
    { id: 12, a: 'CLAUDE', eje: 'Capacidades',
      t: 'Pegué en el chat las veinte páginas de mi informe para que las revisara. En lugar de quedar como texto en la caja del mensaje, todo se convirtió en una tarjetita adjunta, como si fuera un archivo, con las primeras líneas visibles y una etiqueta de texto pegado. Así el mensaje quedó limpio y pude escribir mi pregunta debajo.',
      e: 'Claude convierte los textos largos que se pegan en un adjunto de «texto pegado».',
      r: 'support.claude.com' },
    { id: 13, a: 'CLAUDE', eje: 'Capacidades',
      t: 'Le pedí una calculadora de resistencias en HTML. En el chat no salió el código completo, sino una tarjeta con el título del proyecto. Al abrirla se mostró a la derecha funcionando, con un botón para ver el código, otro para publicarla con un enlace y flechas para pasar entre versiones cada vez que le pedía un cambio.',
      e: 'Son los Artifacts de Claude: piezas de contenido (apps, documentos, diagramas) que se abren en un panel aparte, guardan versiones y se pueden publicar.',
      r: 'support.claude.com · What are artifacts' },
    { id: 14, a: 'CLAUDE', eje: 'Limitaciones',
      t: 'Creé un proyecto para mi tesis y subí mis PDF como conocimiento del proyecto. Debajo apareció una barra con el porcentaje de capacidad usada, y cuando subí muchos archivos más me avisó que, en lugar de leerlos todos completos en cada respuesta, pasaría a buscar dentro de ellos los fragmentos relevantes.',
      e: 'Los proyectos de Claude muestran la capacidad de conocimiento usada y, al superar cierto volumen, activan la búsqueda dentro de los documentos (RAG).',
      r: 'support.claude.com · Projects / RAG for projects' },
    { id: 15, a: 'CLAUDE', eje: 'Capacidades',
      t: 'Antes de escribir abrí un menú de estilos con opciones como Normal, Conciso, Explicativo y Formal. Además me dejó crear un estilo propio: subí dos ensayos que había escrito yo y desde entonces, cuando lo selecciono, redacta imitando mi manera de escribir, con mis frases largas y mi tono.',
      e: 'Los estilos de Claude cambian la forma de responder; se pueden crear estilos personalizados a partir de textos de ejemplo.',
      r: 'support.claude.com · Configuring and using styles' },
    { id: 16, a: 'CLAUDE', eje: 'Capacidades',
      t: 'Trabajando en la terminal con su agente de programación, mientras pensaba aparecía un asterisco animado con palabras curiosas en inglés que iban cambiando. Antes de modificar archivos o ejecutar comandos me pedía permiso, con la opción de aprobar solo esa vez o permitirlo siempre en ese proyecto.',
      e: 'Así se ve Claude Code, el agente de programación de Anthropic: un indicador animado mientras trabaja y un sistema de permisos para editar archivos y ejecutar comandos.',
      r: 'docs.claude.com · Claude Code' },
    { id: 17, a: 'CLAUDE', eje: 'Limitaciones',
      t: 'Le pedí una foto realista de un robot soldador para mi presentación. Me respondió que no podía crear imágenes de ese tipo, pero me ofreció un diagrama hecho con código, y en efecto me entregó un esquema vectorial limpio del robot con sus partes señaladas, que pude descargar y poner en las diapositivas.',
      e: 'Claude no genera fotos ni ilustraciones; sí produce diagramas y gráficos con código (SVG, HTML).',
      r: 'support.claude.com/en/articles/9002504' },
    { id: 18, a: 'CLAUDE', eje: 'Limitaciones',
      t: 'Un compañero se puso a insultar al asistente durante muchos mensajes para «probarlo». Después de intentar varias veces reconducir la charla, el asistente dio por terminada la conversación y ya no dejó escribir más en ese chat. Sí le permitió abrir uno nuevo y editar mensajes anteriores para seguir por otro camino.',
      e: 'Algunos modelos de Claude pueden terminar conversaciones en casos extremos de abuso persistente; es parte del trabajo de Anthropic sobre bienestar del modelo.',
      r: 'anthropic.com/research/end-subset-conversations' },
    { id: 19, a: 'CLAUDE', eje: 'Capacidades',
      t: 'Le pregunté «¿en qué quedamos la semana pasada con el proyecto del puente?». En pantalla vi que primero buscó en mis conversaciones anteriores, con un paso visible que mostraba los chats que estaba consultando, y después retomó el tema con los datos correctos, citando la conversación donde lo habíamos hablado.',
      e: 'Claude puede buscar en chats anteriores cuando el usuario lo pide, y muestra esa búsqueda como un paso visible.',
      r: 'support.claude.com · Search and reference past chats' },
    { id: 20, a: 'CLAUDE', eje: 'Generosidad',
      t: 'Hice en el chat un tutor interactivo de física que tiene IA adentro y lo publiqué con un enlace. Cuando mis compañeros lo usan, la IA de la app les responde, pero ese consumo se descuenta de la cuenta de cada compañero, no de la mía, así que pude compartirlo con todo el curso sin pagar más.',
      e: 'Los artifacts de Claude con IA integrada cobran el uso a la cuenta de quien los usa, no a la de quien los creó.',
      r: 'anthropic.com/news · Build and share AI-powered apps with Claude' },

    /* ===== GEMINI · Google ===== */
    { id: 21, a: 'GEMINI', eje: 'Limitaciones',
      t: 'Debajo de la caja donde escribo aparece siempre una advertencia. Lo que me llamó la atención es que no solo dice que puede cometer errores: aclara que puede equivocarse incluso sobre personas, y pide verificar sus respuestas. Lo noté después de que me inventó un dato sobre un profesor de la universidad.',
      e: 'El aviso de Gemini menciona explícitamente que puede cometer errores «incluso sobre personas».',
      r: 'support.google.com/gemini' },
    { id: 22, a: 'GEMINI', eje: 'Capacidades',
      t: 'Activé la investigación profunda para un informe de energías renovables. Antes de buscar nada me mostró un plan con los pasos que pensaba seguir, con un botón para editarlo y otro para empezar. Lo ajusté, aprobé, y al final me ofreció exportar el informe directamente a un documento de mi cuenta de la misma empresa.',
      e: 'Deep Research de Gemini presenta un plan editable antes de empezar y permite exportar el informe a Google Docs.',
      r: 'support.google.com/gemini · Deep Research' },
    { id: 23, a: 'GEMINI', eje: 'Capacidades',
      t: 'Escribí una arroba en la caja del mensaje y apareció una lista de aplicaciones de la misma empresa para conectar: el correo, el almacenamiento en la nube, los mapas y la plataforma de videos. Elegí la del correo y le pedí que buscara el mensaje del profesor con la fecha del parcial, y me lo encontró.',
      e: 'Gemini se conecta con apps de Google (Gmail, Drive, Maps, YouTube), que se pueden invocar con @ en el mensaje.',
      r: 'support.google.com/gemini · Apps' },
    { id: 24, a: 'GEMINI', eje: 'Limitaciones',
      t: 'Dudé de una respuesta y usé la opción de verificarla. El sistema revisó cada afirmación en el buscador de su fabricante y pintó algunas frases de verde, porque encontró contenido parecido, y otras de naranja, porque encontró algo distinto o nada. Así supe cuáles partes revisar con más cuidado.',
      e: 'La función «Verificar respuesta» de Gemini contrasta el texto con la Búsqueda de Google y lo resalta en verde o naranja.',
      r: 'support.google.com/gemini/answer/14143489' },
    { id: 25, a: 'GEMINI', eje: 'Limitaciones',
      t: 'Las imágenes que me generó para el afiche traían en una esquina un pequeño destello, una estrella de cuatro puntas, como marca visible. Investigando supe que además llevan una marca de agua invisible, incrustada en los píxeles, que el propio fabricante puede detectar para saber si la imagen fue hecha con su IA.',
      e: 'Las imágenes de Gemini llevan una marca visible y SynthID, la marca de agua invisible de Google DeepMind.',
      r: 'deepmind.google/models/synthid/' },
    { id: 26, a: 'GEMINI', eje: 'Capacidades',
      t: 'Creé un asistente personalizado con instrucciones fijas para revisar mis informes de laboratorio. El fabricante les pone a estos asistentes el nombre de una piedra preciosa. Aparecen en la barra lateral junto a otros ya hechos, como un entrenador de aprendizaje, un compañero de lluvia de ideas o un asesor de programación.',
      e: 'Son los Gems de Gemini: asistentes personalizados con instrucciones y archivos propios.',
      r: 'support.google.com/gemini · Gems' },
    { id: 27, a: 'GEMINI', eje: 'Identidad',
      t: 'En mi celular Android mantuve presionado el botón de encendido y, en lugar del asistente de siempre, se abrió una ventana flotante de esta IA sobre la app que estaba usando. Le pregunté por lo que estaba viendo en la pantalla y me lo explicó sin que tuviera que hacer captura ni copiar nada.',
      e: 'Gemini reemplazó al Asistente de Google en Android y puede responder sobre lo que se ve en la pantalla.',
      r: 'blog.google/products-and-platforms/products/gemini/google-assistant-gemini-mobile/' },
    { id: 28, a: 'GEMINI', eje: 'Capacidades',
      t: 'Cuando terminó un informe de investigación, me ofreció convertirlo en un audio. Lo que generó fue una conversación entre dos presentadores con voces distintas que discutían el tema con naturalidad, se interrumpían y hacían chistes. Lo escuché en el bus camino a la universidad como si fuera un pódcast.',
      e: 'Audio Overview, nacido en NotebookLM, convierte documentos e informes de Gemini en un diálogo de dos presentadores.',
      r: 'support.google.com/gemini/answer/16047373' },
    { id: 29, a: 'GEMINI', eje: 'Capacidades',
      t: 'Estaba en el correo de la universidad y abrí un panel lateral con la IA sin salir de la bandeja de entrada. Le pedí que resumiera los diez correos del profesor sobre el proyecto y que redactara una respuesta con base en un documento de mi carpeta en la nube. Todo pasó dentro de la misma suite de oficina.',
      e: 'Gemini está integrado en Gmail, Docs y Drive como panel lateral.',
      r: 'gemini.google/subscriptions' },
    { id: 30, a: 'GEMINI', eje: 'Capacidades',
      t: 'Le pedí sitios para una salida de campo cerca de Sotaquirá. En vez de una simple lista, me respondió con tarjetas de lugares con su calificación, horarios y fotos, y un mapa interactivo dentro de la misma respuesta, donde podía tocar cada punto y abrir la ruta en la aplicación de mapas de la misma empresa.',
      e: 'Gemini usa Google Maps para responder con lugares, calificaciones y mapas interactivos.',
      r: 'support.google.com/gemini · Google Maps' },

    /* ===== PERPLEXITY · Perplexity AI ===== */
    { id: 31, a: 'PERPLEXITY', eje: 'Identidad',
      t: 'Al hacer cualquier pregunta, lo primero que aparece no es el texto: son las fuentes que encontró, en tarjetas en la parte de arriba. La respuesta llega después, con números pequeños al lado de cada frase. Arriba hay pestañas para cambiar entre la respuesta, las imágenes, la lista de fuentes y los pasos de búsqueda que siguió.',
      e: 'Así está organizada una respuesta de Perplexity: fuentes primero, citas numeradas y pestañas de respuesta, imágenes, fuentes y pasos.',
      r: 'perplexity.ai/hub/getting-started' },
    { id: 32, a: 'PERPLEXITY', eje: 'Capacidades',
      t: 'Al final de cada respuesta, sin falta, aparece una lista de preguntas relacionadas que puedo tocar para seguir investigando. Así terminé leyendo sobre el reciclaje de baterías cuando solo había preguntado por su vida útil. Es casi como ir pasando de enlace en enlace en una enciclopedia, pero con respuestas citadas.',
      e: 'Perplexity sugiere preguntas relacionadas al final de cada respuesta para continuar la búsqueda.',
      r: 'perplexity.ai/hub/getting-started' },
    { id: 33, a: 'PERPLEXITY', eje: 'Capacidades',
      t: 'Una respuesta no me convenció. Usé la opción de reescribir y me dejó escoger con qué modelo volver a generarla: uno de OpenAI, uno de Google, uno de Anthropic o el de la propia plataforma. Comparé las dos versiones sobre las mismas fuentes y me quedé con la más precisa para mi trabajo.',
      e: 'Perplexity permite regenerar una respuesta con otro modelo, de distintos fabricantes, sobre la misma búsqueda.',
      r: 'perplexity.ai/help-center/en/articles/10354919' },
    { id: 34, a: 'PERPLEXITY', eje: 'Limitaciones',
      t: 'Le pedí un poema corto sobre mi perro, algo que no necesita internet. Aun así, empezó buscando en la web y me mostró fuentes de sitios de poesía antes de escribir el poema. Me di cuenta de que su manera de trabajar es buscar primero para casi todo, incluso cuando la tarea es puramente creativa.',
      e: 'Perplexity es un motor de respuestas: su comportamiento por defecto es buscar en la web y citar antes de responder.',
      r: 'perplexity.ai/help-center/en/articles/10352155' },
    { id: 35, a: 'PERPLEXITY', eje: 'Capacidades',
      t: 'En el selector de fuentes desactivé la web general y elegí la opción social. La respuesta se armó con discusiones de foros como Reddit: opiniones de usuarios, experiencias personales y recomendaciones, en lugar de artículos o noticias. Me sirvió para saber qué piensan los usuarios de un sensor antes de comprarlo.',
      e: 'Perplexity permite escoger las fuentes de la búsqueda: web, académicas, sociales (foros) y financieras.',
      r: 'perplexity.ai/help-center · Sources' },
    { id: 36, a: 'PERPLEXITY', eje: 'Generosidad',
      t: 'En la versión gratuita, cada búsqueda avanzada se descontaba de un cupo diario muy pequeño, y lo veía bajar. Cuando se agotó no me bloqueó ni me hizo esperar: siguió respondiendo con búsquedas básicas, que son ilimitadas, solo que con menos pasos de investigación y menos fuentes por respuesta.',
      e: 'El plan gratuito de Perplexity tiene búsquedas básicas ilimitadas y un cupo diario pequeño de búsquedas Pro.',
      r: 'perplexity.ai/help-center/en/articles/10352901' },
    { id: 37, a: 'PERPLEXITY', eje: 'Identidad',
      t: 'La pantalla de inicio tiene una sección para descubrir las noticias del día. Cada noticia está convertida en un resumen escrito por la IA, con sus fuentes enlazadas, y al final puedo hacer preguntas sobre ella como en cualquier búsqueda. Así me enteré de un lanzamiento de robótica sin abrir un periódico.',
      e: 'Discover es el feed de noticias de Perplexity: resúmenes con fuentes sobre los que se puede seguir preguntando.',
      r: 'perplexity.ai/discover' },
    { id: 38, a: 'PERPLEXITY', eje: 'Capacidades',
      t: 'Instalé el navegador de esta empresa. En cualquier página puedo abrir el asistente al lado y pedirle que compare los productos de las pestañas abiertas, que llene un formulario o que resuma un video que estoy viendo. Es gratuito y lo uso tanto en el computador como en el celular.',
      e: 'Comet es el navegador de Perplexity, gratuito, con su asistente integrado.',
      r: 'perplexity.ai/comet' },
    { id: 39, a: 'PERPLEXITY', eje: 'Limitaciones',
      t: 'Me dio una cifra equivocada del salario mínimo. Al tocar el numerito junto a la frase, vi que el dato venía de un blog desactualizado: el modelo no lo inventó, lo copió fielmente de esa fuente. Entendí que su forma de equivocarse es distinta: el error se puede rastrear, pero hay que abrir la fuente para verlo.',
      e: 'Perplexity cita cada afirmación; si la fuente está errada, la respuesta también lo estará. La cita permite rastrear el error.',
      r: 'perplexity.ai/hub/getting-started' },
    { id: 40, a: 'PERPLEXITY', eje: 'Capacidades',
      t: 'Terminé una investigación larga en un hilo y la convertí, con un clic, en una página pública con aspecto de artículo de revista: título, secciones, imágenes y las fuentes al final. Pude editar cada sección, cambiar el público al que iba dirigida y compartirla con un enlace con mi grupo.',
      e: 'Pages de Perplexity convierte un hilo de búsqueda en un artículo publicable con fuentes.',
      r: 'perplexity.ai/hub/blog/perplexity-pages' }
  ]
};
