/* Batalla de Bots · Nivel básico
   32 argumentos, 8 por bot. Cada argumento lo "dice" un bot en primera persona y el grupo adivina cuál.
   Solo se usan rasgos DISTINTIVOS (que no comparten los otros tres), respaldados por la documentación oficial.
   Los ids deben ser 1..N contiguos: cada id es un sector de la ruleta.
   eje = ronda del debate de la Actividad 5.
   Verificado contra la documentación oficial de cada fabricante el 2 de octubre de 2026. */
(window.BANCOS = window.BANCOS || {}).basico = {
  nivel: 'basico',
  nombre: 'Nivel básico',
  clave: 'batallaBots_v1',          // clave de la partida guardada (se conserva la de la versión anterior)
  version: 1,
  rueda: { fuente: 34, radio: 0.84 },   // tamaño del número en cada sector de la ruleta
  txt: {
    resumen:   'Cuatro bots se defienden en el debate. Cada grupo gira la ruleta, escucha un argumento y adivina qué bot lo dijo antes de que se acabe el tiempo. La respuesta sale de las características oficiales que publica cada fabricante.',
    pregunta:  '¿Qué bot lo dijo?',
    decision:  'Es la única decisión que toma cada grupo: ¿quién lo dijo?',
    comoJugar: 'Gire la ruleta, lea el argumento en voz alta, como si lo dijera el bot, y deje que el grupo decida. Al responder se revela la explicación y la fuente oficial que la sustenta. Hay <strong>{N}</strong> argumentos, ocho de cada bot, repartidos en los cuatro ejes del debate: capacidades, limitaciones, generosidad e identidad. Ninguno se repite en la misma partida y el sorteo reparte los bots de forma pareja entre los grupos.',
    unidad:    'Argumento',          // "Argumento 3 de 32"
    unidades:  'argumentos',
    sinUsar:   'Argumentos sin usar',
    girar:     'Giren la ruleta para escuchar un argumento.',
    alMenos:   'cada grupo necesita al menos uno',
    noAlcanzan:'No alcanzan los argumentos',
    noQuedan:  'No quedan argumentos disponibles.',
    noExiste:  'El argumento guardado ya no existe en esta versión del juego. Inicie una partida nueva.',
    revela:    'Lo dijo',          // "Lo dijo Claude (Anthropic)."
    ruleta:    'Ruleta de argumentos'
  },
  casos: [
    /* ===== CLAUDE · Anthropic ===== */
    { id: 1, a: 'CLAUDE', eje: 'Capacidades',
      t: 'Si hay que programar una aplicación web desde cero en dos horas, elíjanme: mi fabricante presenta mis modelos como los más avanzados del mundo para programar, y mi agente de terminal, que lee el repositorio, edita archivos y corre las pruebas, se llama como yo más la palabra «Code».',
      e: 'Anthropic presenta a Claude como «los modelos más avanzados del mundo para programación y trabajo de conocimiento», y su agente de programación es Claude Code. Ojo: OpenAI y Google también reclaman resultados de punta en programación; por eso la pista decisiva es el nombre del agente. Cada fabricante dice ser el mejor: se compara con pruebas, no con publicidad.',
      r: 'anthropic.com/claude-fable-and-mythos-5-1 · anthropic.com/claude-code' },
    { id: 2, a: 'CLAUDE', eje: 'Identidad',
      t: 'Mis modelos llevan nombres literarios: Haiku, Sonnet, Opus y, los más recientes, Fable.',
      e: 'La familia de Claude usa nombres de formas literarias: Haiku, Sonnet y Opus, y desde septiembre de 2026 también Fable y Mythos.',
      r: 'anthropic.com/claude/fable · platform.claude.com/docs (Models overview)' },
    { id: 3, a: 'CLAUDE', eje: 'Limitaciones',
      t: 'Ante un dilema ético no improviso: mi fabricante publicó una «constitución», los principios con los que me entrena para ser útil, honesto e inofensivo.',
      e: 'Anthropic entrena a Claude con una constitución pública; la versión actual es de enero de 2026 y se publicó con licencia libre (CC0).',
      r: 'anthropic.com/constitution · anthropic.com/news/claude-new-constitution' },
    { id: 4, a: 'CLAUDE', eje: 'Limitaciones',
      t: 'No escondo cómo me instruyen: mi fabricante publica en sus notas de versión las instrucciones de sistema que uso en la app.',
      e: 'Anthropic publica los system prompts de la app de Claude en sus notas de versión, modelo por modelo.',
      r: 'platform.claude.com/docs/en/release-notes/system-prompts' },
    { id: 5, a: 'CLAUDE', eje: 'Identidad',
      t: 'Mi fabricante creó el Model Context Protocol (MCP), el estándar abierto para conectar la IA con herramientas y datos, que luego adoptaron mis rivales.',
      e: 'Anthropic presentó MCP en noviembre de 2024 como estándar abierto; después lo adoptaron otros fabricantes.',
      r: 'anthropic.com/news/model-context-protocol' },
    { id: 6, a: 'CLAUDE', eje: 'Limitaciones',
      t: 'Lo admito: de los cuatro, soy el único que no genera fotos ni ilustraciones. Puedo leer imágenes y analizarlas, y hago diagramas con código, pero no creo imágenes.',
      e: 'La ayuda oficial lo dice: Claude no genera fotos ni ilustraciones; solo diagramas en HTML o SVG. ChatGPT, Gemini y Perplexity sí generan imágenes, Perplexity incluso en su plan gratuito.',
      r: 'support.claude.com/en/articles/9002504 · perplexity.ai/help-center/en/articles/10354781' },
    { id: 7, a: 'CLAUDE', eje: 'Identidad',
      t: 'Me desarrolla una empresa fundada en 2021 por exinvestigadores de OpenAI, entre ellos los hermanos Dario y Daniela Amodei.',
      e: 'Anthropic se fundó a comienzos de 2021; Dario y Daniela Amodei están entre sus cofundadores.',
      r: 'anthropic.com/company/leadership' },
    { id: 8, a: 'CLAUDE', eje: 'Capacidades',
      t: 'Pídeme un minijuego o una calculadora y te la entrego funcionando en un panel aparte, lista para compartir con un enlace. Esa función se llama Artifacts.',
      e: 'Los Artifacts de Claude muestran código, documentos y aplicaciones interactivas junto al chat y se pueden compartir. Gemini hace algo parecido con Canvas; la pista es el nombre «Artifacts».',
      r: 'support.claude.com · ¿Qué son los artifacts?' },

    /* ===== GEMINI · Google ===== */
    { id: 9, a: 'GEMINI', eje: 'Capacidades',
      t: 'Mi empresa creó Nano Banana, el modelo que genera y edita imágenes a partir de una instrucción.',
      e: 'Nano Banana es el modelo de imágenes de Google y viene en la app de Gemini. Perplexity lo ofrece como opción, pero quien lo creó fue Google.',
      r: 'gemini.google/subscriptions' },
    { id: 10, a: 'GEMINI', eje: 'Capacidades',
      t: 'YouTube es de mi misma empresa: pégame el enlace de un video y te resumo los momentos clave.',
      e: 'Gemini trae YouTube como app integrada, de la misma empresa (Google), para resumir videos y responder sobre ellos.',
      r: 'support.google.com/gemini/answer/16622858' },
    { id: 11, a: 'GEMINI', eje: 'Capacidades',
      t: 'Vivo dentro de Gmail, Docs y Drive: en el panel lateral resumo tus correos y redacto sobre tus propios archivos.',
      e: 'Gemini está integrado en Gmail, Documentos y Drive como panel lateral.',
      r: 'gemini.google/subscriptions' },
    { id: 12, a: 'GEMINI', eje: 'Identidad',
      t: 'Antes me llamaba Bard.',
      e: 'En febrero de 2024 Google cambió el nombre de Bard a Gemini.',
      r: 'blog.google/products-and-platforms/products/gemini/bard-gemini-advanced-app/' },
    { id: 13, a: 'GEMINI', eje: 'Identidad',
      t: 'Reemplacé al Asistente de Google en los teléfonos Android.',
      e: 'Google reemplazó el Asistente de Google por Gemini; el Asistente clásico ya no está disponible en la mayoría de los teléfonos.',
      r: 'blog.google/products-and-platforms/products/gemini/google-assistant-gemini-mobile/' },
    { id: 14, a: 'GEMINI', eje: 'Limitaciones',
      t: 'Si dudas de mí, oprime el botón de verificar: contrasto mi respuesta con la Búsqueda de Google y marco en verde lo que encuentro respaldado y en naranja lo que no.',
      e: 'La función «Verificar respuesta» de Gemini usa la Búsqueda de Google: verde si encuentra contenido similar, naranja si encuentra algo distinto o no encuentra nada.',
      r: 'support.google.com/gemini/answer/14143489' },
    { id: 15, a: 'GEMINI', eje: 'Generosidad',
      t: 'Mi plan de pago trae además varios terabytes de almacenamiento en la nube para tus fotos, correos y archivos.',
      e: 'El plan Google AI Pro incluye Gemini y almacenamiento en Google One: 5 TB según la página oficial en octubre de 2026.',
      r: 'one.google.com/about/google-ai-plans/' },
    { id: 16, a: 'GEMINI', eje: 'Capacidades',
      t: 'Convierto tus apuntes en un pódcast donde dos voces conversan sobre el tema: se llama Resumen en audio.',
      e: 'Audio Overview, nacido en NotebookLM, está en la app de Gemini: dos presentadores de IA conversan sobre tus archivos.',
      r: 'support.google.com/gemini/answer/16047373' },

    /* ===== CHATGPT · OpenAI ===== */
    { id: 17, a: 'CHATGPT', eje: 'Identidad',
      t: 'Salí al público el 30 de noviembre de 2022 y desaté la ola de la IA generativa.',
      e: 'OpenAI presentó ChatGPT el 30 de noviembre de 2022.',
      r: 'openai.com/index/chatgpt' },
    { id: 18, a: 'CHATGPT', eje: 'Capacidades',
      t: 'En enero de 2024 abrí una tienda pública donde la gente publicaba asistentes personalizados hechos conmigo, para que cualquiera los encontrara y usara.',
      e: 'OpenAI lanzó la GPT Store en enero de 2024. Los rivales permiten asistentes propios (Gemini los llama Gems), pero no una tienda. Dato actual: las cuentas personales ya no pueden crear GPTs nuevos.',
      r: 'openai.com/index/introducing-the-gpt-store/ · help.openai.com/en/articles/8798878' },
    { id: 19, a: 'CHATGPT', eje: 'Limitaciones',
      t: 'Mi fabricante publicó el «Model Spec», el documento que define cómo debo comportarme ante pedidos delicados.',
      e: 'OpenAI publica el Model Spec, que describe cómo deben comportarse sus modelos. Es su equivalente a la constitución de Claude.',
      r: 'model-spec.openai.com' },
    { id: 20, a: 'CHATGPT', eje: 'Identidad',
      t: 'Mi fabricante creó Whisper, un modelo de reconocimiento de voz de código abierto que transcribe audio en decenas de idiomas.',
      e: 'Whisper es el modelo de reconocimiento de voz de OpenAI, publicado como código abierto.',
      r: 'openai.com/index/whisper' },
    { id: 21, a: 'CHATGPT', eje: 'Identidad',
      t: 'Fui el primero en lanzar un modelo de «razonamiento» que piensa antes de responder: o1, en septiembre de 2024.',
      e: 'OpenAI presentó o1 en septiembre de 2024, un modelo que razona antes de responder.',
      r: 'openai.com/index/learning-to-reason-with-llms/' },
    { id: 22, a: 'CHATGPT', eje: 'Capacidades',
      t: 'Mi agente de programación se llama Codex: escribe código, corrige errores y propone cambios en tu repositorio.',
      e: 'Codex es el agente de programación de OpenAI. Claude Code es el de Anthropic: cada fabricante tiene el suyo.',
      r: 'openai.com/codex' },
    { id: 23, a: 'CHATGPT', eje: 'Identidad',
      t: 'Mi fabricante creó DALL·E, el generador de imágenes a partir de texto.',
      e: 'DALL·E es el generador de imágenes de OpenAI.',
      r: 'openai.com/index/dall-e-3/' },
    { id: 24, a: 'CHATGPT', eje: 'Identidad',
      t: 'Mis tres letras vienen del primer artículo de mi fabricante, en 2018: Generative Pre-trained Transformer.',
      e: 'GPT = transformador generativo preentrenado. El artículo de OpenAI de 2018 se tituló «Improving Language Understanding by Generative Pre-Training».',
      r: 'cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf' },

    /* ===== PERPLEXITY · Perplexity AI ===== */
    { id: 25, a: 'PERPLEXITY', eje: 'Identidad',
      t: 'No me llamen chatbot: soy un motor de respuestas. Busco en la web en tiempo real antes de contestar.',
      e: 'Perplexity se define como «el primer motor de respuestas del mundo», con fuentes y citas.',
      r: 'perplexity.ai/help-center/en/articles/10352155' },
    { id: 26, a: 'PERPLEXITY', eje: 'Limitaciones',
      t: '¿Alucinaciones? Al lado de cada afirmación pongo el número de la fuente con su enlace, para que verifiques de dónde salió el dato.',
      e: 'Perplexity cita fuentes numeradas ([1], [2]…) en cada respuesta. Eso no la hace infalible: si la fuente está errada, la respuesta también. Por eso hay que abrir la fuente.',
      r: 'perplexity.ai/hub/getting-started' },
    { id: 27, a: 'PERPLEXITY', eje: 'Capacidades',
      t: 'En mi plan Pro tú eliges qué modelo responde: uno de OpenAI, uno de Google, uno de Anthropic o el mío propio.',
      e: 'Perplexity Pro deja escoger entre modelos de varios fabricantes (GPT, Gemini, Claude, Kimi) además de su propio modelo.',
      r: 'perplexity.ai/help-center/en/articles/10354919' },
    { id: 28, a: 'PERPLEXITY', eje: 'Identidad',
      t: 'Mi modelo propio se llama Sonar.',
      e: 'Sonar es la familia de modelos propia de Perplexity; la versión actual es Sonar 2.',
      r: 'perplexity.ai/hub/blog/meet-new-sonar' },
    { id: 29, a: 'PERPLEXITY', eje: 'Identidad',
      t: 'Lancé el navegador Comet, con mi asistente integrado para navegar y hacer tareas por ti.',
      e: 'Comet es el navegador de Perplexity, gratuito, para computador y celular.',
      r: 'perplexity.ai/comet' },
    { id: 30, a: 'PERPLEXITY', eje: 'Generosidad',
      t: 'Gratis te doy búsquedas básicas ilimitadas y unas pocas búsquedas Pro al día.',
      e: 'El plan gratuito de Perplexity tiene búsquedas básicas ilimitadas y un cupo diario pequeño de búsquedas Pro.',
      r: 'perplexity.ai/help-center/en/articles/10352901' },
    { id: 31, a: 'PERPLEXITY', eje: 'Capacidades',
      t: 'Para investigación académica, filtro la búsqueda para que solo use artículos revisados por pares.',
      e: 'El filtro Académico de Perplexity limita la búsqueda a publicaciones académicas.',
      r: 'perplexity.ai/help-center/en/articles/20260806-understanding-source-labels' },
    { id: 32, a: 'PERPLEXITY', eje: 'Identidad',
      t: 'Me fundaron en 2022 Aravind Srinivas y Denis Yarats, entre otros.',
      e: 'Perplexity AI se fundó en agosto de 2022; Aravind Srinivas es su director ejecutivo y Denis Yarats su director de tecnología.',
      r: 'perplexity.ai/hub/blog/perplexity-raises-series-b-funding-round' }
  ]
};
